schedules:
  commit:
    # Run short suite on commit with enough C* versions to get full protocol version coverage.
    schedule: per_commit
    matrix:
      exclude:
        # Exclude all builds on old jdk versions
        - jabba: ['zulu_jdk6','zulu_jdk7']
        # Exclude java8 with all versions except latest
        - jabba: oracle_jdk8
          cassandra: ['2.2', '3.0']
        # Exclude java11 with all versions except latest
        - jabba: openjdk_jdk11
          cassandra: ['2.1', '2.2', '3.0']
    env_vars: |
      TEST_GROUP="short"
    disable_commit_status: true
    disable_pull_requests: true
    notify:
      slack: java-driver-dev-bots
  nightly:
    # Run full suite nightly on change for all primary branches if they have changes.
    schedule: nightly
    branches:
      # regex matches primary branch format (2.1, 3.x, 3.0.x, 3.1.x, etc).
      include: ["/\\d+(\\.[\\dx]+)+/"]
    env_vars: |
      TEST_GROUP="long"
    disable_commit_status: true
    disable_pull_requests: true
    notify:
      slack: java-driver-dev-bots
  adhoc:
    # Adhoc job for non-primary braches that doesn't have a schedule but may be used to run all configs.
    schedule: adhoc
    branches:
      # regex matches primary branch format (2.1, 3.x, 3.0.x, 3.1.x, etc).
      exclude: ["/\\d+(\\.[\\dx]+)+/"]
    env_vars: |
      TEST_GROUP="long"
    disable_commit_status: true
    disable_pull_requests: true
    notify:
      slack: java-driver-dev-bots
jabba:
  - zulu_jdk6
  - zulu_jdk7
  - oracle_jdk8
  - openjdk_jdk11
os:
  - ubuntu/bionic64/java-driver
cassandra:
  - '2.1'
  - '2.2'
  - '3.0'
  - '3.11'
build:
  - script: |
      jabba use default
      export JAVA8_HOME=$JAVA_HOME
      export MAVEN_HOME=/home/jenkins/.mvn/apache-maven-3.2.5
      export PATH=$MAVEN_HOME/bin:$PATH
      mvn -B -V install -DskipTests
      jabba use $JABBA_JDK_NAME
      mvn -B -V verify --fail-never -P$TEST_GROUP -Dcom.datastax.driver.TEST_BASE_NODE_WAIT=120 -Dcom.datastax.driver.NEW_NODE_DELAY_SECONDS=100 -Dcassandra.version=$CCM_CASSANDRA_VERSION -Dccm.java.home=$CCM_JAVA_HOME -Dccm.path=$CCM_JAVA_HOME/bin -Dccm.maxNumberOfNodes=3 -DfailIfNoTests=false -Dmaven.test.failure.ignore=true -Dmaven.javadoc.skip=true
      mvn -B -V verify --fail-never -Pisolated -Dcom.datastax.driver.TEST_BASE_NODE_WAIT=120 -Dcom.datastax.driver.NEW_NODE_DELAY_SECONDS=100 -Dcassandra.version=$CCM_CASSANDRA_VERSION -Dccm.java.home=$CCM_JAVA_HOME -Dccm.path=$CCM_JAVA_HOME/bin -Dccm.maxNumberOfNodes=3 -DfailIfNoTests=false -Dmaven.test.failure.ignore=true -Dmaven.javadoc.skip=true
  - xunit:
    - "**/target/surefire-reports/TEST-*.xml"
    - "**/target/failsafe-reports/TEST-*.xml" 
