jabba:
  - openjdk_jdk12
  - openjdk_jdk11
  - oracle_jdk8
os:
  - ubuntu/bionic64/java-driver
cassandra:
  - '2.1'
  - '2.2'
  - '3.0'
  - '3.11'
matrix:
  exclude:
    # Exclude java8 with all versions except latest
    - jabba: oracle_jdk8
      cassandra: ['2.2', '3.0']
    # Exclude java11 with all versions except latest
    - jabba: openjdk_jdk11
      cassandra: ['2.1', '2.2', '3.0']
    # Exclude java11 with all versions except latest
    - jabba: openjdk_jdk12
      cassandra: ['2.1', '2.2', '3.0']
build:
  - script: |
      env|sort
      jabba use default
      export MAVEN_HOME=/home/jenkins/.mvn/apache-maven-3.3.9
      export PATH=$MAVEN_HOME/bin:$PATH
      mvn -B -V install -DskipTests
      jabba use $JABBA_JDK_NAME
      mvn -B -V verify --batch-mode --show-version -Dccm.version=$CCM_CASSANDRA_VERSION -Dmaven.javadoc.skip=true
  - xunit:
    - "**/target/surefire-reports/TEST-*.xml"
    - "**/target/failsafe-reports/TEST-*.xml"
  - jacoco: true
disable_commit_status: true
notify:
  slack: java-driver-dev-bots
